apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: muse-spark

resources:
  - ../../base
  - registry-secret.yaml

images:
  - name: ghcr.io/gateszhangc/muse-spark
    newName: ghcr.io/gateszhangc/muse-spark
    newTag: 979d0d849f8bcfc7225b9622559e3eb87ef9c137

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/part-of: muse-spark
      app.kubernetes.io/environment: production
