apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dokploy-fleet-ghcr
  namespace: muse-spark
spec:
  encryptedData:
    .dockerconfigjson: AgAOrWOAekZ2BUqj+5Ek9wE9a/e/llVk17R1hQwGe5tswwhRJXyeEipgnAxP6rNAvslIfj8i5osH5G2Hq+J30rzE4NGuKHY7IGPp7rIosSc7yXnHAKiSvA4D4v3b60Cbd0xwIipLbpvinKN9jrg2tw+2+Tg6aM63bXWzLcvlxWq8qRV2zDKkHWVfyinqzXGJwQylkTnXJVxY2c0DSzaUCcWZUyfr84T+3vs/Vd8ckAKAMsduysSvqOWnw16QqALqtht6K/XGsSHjaaD6W8oNJ/4Y/o9CL+SpX1iVvry7kvm4k7F1Mb59iTpnyKhLnYTvkN+7WAStj+Zz93XHeug79pX3n3B/suQvdKGdbZwiCiZiZ4jV0PAPFzdXtDygZ5l+iqPgz9f+3LextFjf4yUUKcCjLmEmI958vtcaXtF8NkRVoTj7CejGAROkKk9eJ4bJGLHRK1FkFBkLkl2miGb+9tKFf+Fs9+qcMf0iTPQToL1iZWJmJDonJj8EIcnyJs79Yr7SVrk4Oq+Y3WWicmlFh/wqx2riJb5sk7vihEnR/m/w52VuXGHto73pkAmcTr2oZkQMXrqALy9SEK7gPZMNaJgFZxnM4iCFGxlIdBoVZJw4c15SY18vvk2f18iSCtR9isdtHhKjygQgkkJ9Fmquc/MlyVYjb8f/V9vu8JziASPbDqsH10wJfl+aevz/jn6jCDIcn//8JRMjyN1Qn2cBM9mS7W4TO0vl8eH5vPwbXBUQqgwVY0tOUYlyaXtMM8AqGkJEm5sL2ysqplK0wRAaFOu4esbDgCpkX86kJvN+72B8lF1+GNaK+QmNRPSvA1MzdWEPs374xt3oph2wbuP83UBTxue/uys0hvLQhxipseu69BuwYPBpiQb+HOf0Jbr7AN7zlbQMz1PA9pulajKHmu4WVzCAUL0fwpHwJ7HkZ3QuFQ9WP+f9bBip
  template:
    metadata:
      labels:
        app.kubernetes.io/name: muse-spark
        app.kubernetes.io/part-of: muse-spark
      name: dokploy-fleet-ghcr
      namespace: muse-spark
    type: kubernetes.io/dockerconfigjson
