apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: muse-spark
  namespace: argocd
spec:
  project: muse-spark
  source:
    repoURL: https://github.com/gateszhangc/muse-spark.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: muse-spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
